# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170323_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_details',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
