# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_album_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_details',
            field=models.CharField(max_length=100),
        ),
    ]
