# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170323_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_details',
            field=models.CharField(max_length=250),
        ),
    ]
